src/tasks/global/test.js, src/utils/task/getParams.js
* To fix some bugs in the keg-cli, namely:
* calling a command with two flags that have the same starting character
* calling a command with a flag that has no value (should be interpreted as `true`, but often wasn't)
* `src/tasks/global/test.js`
* just added some more test flags
* `src/utils/task/getParams.js`
* ensured that both the key and value gets removed from options array during options parsing, preventing bugs for multiple flags with the same first character
* updated `matchParamType`'s checking of task keys for the value. Before, it only checked if the value matched the current key's match types. I updated it to check all possible option keys (including aliases). This way you can pass something like `keg do command --foo b=2` and foo will be `true`, which wasn't working for me …
=> Options bug fixes

src/tasks/network/listProcessesUsingPort.js
*  when printing out the keg network -h , it prints list  twice
* because the key name of the export does not match the name of the task
*  Change the key name of the export object
* updated the key name
* `keg net -h` should only print out `list` once
=> updated export name to task name for net

src/libs/logger/showHelp.js, src/tasks/core/start.js
**Ticket**: n/a
* I pulled the latest changes on `keg-cli` and was just poking around to get a better understanding of it
* I noticed on certain tasks, it contains more than just a `description` key and I figured it would be helpful to be able to print them out when using.`-help`
* if an option is passed in before the `help` keyword, it will print out any extra details on that option item (if available)
* it will only print out the help for 1 option for now 
* help users see the options in detail when going through the `help` options
* `src/libs/logger/showHelp.js`
* added a new method to be able to pull in detail info for a given option item
* run any help command with an option item passed in (not alias)
* example: `keg core start docker -h`
- output: …
=> Ability to print option details

src/__mocks__/helpers/globalConfig.js, src/constants/docker/containers.js, src/libs/docker/image.js, src/tasks/cli/env/set.js, src/tasks/cli/env/unset.js, src/utils/defaultEnvs/addDefaultEnv.js, src/utils/defaultEnvs/removeDefaultEnv.js, src/utils/helpers/confirmExec.js
* These changes are part of a migration to how docker images are handled
* They were extracted out from a larger amount of changes to make the PR more consumable
* All changes may not make sense in this isolated context, but they are needed within a larger context
* Add ENV for setting the keg-hub root dir ( KEG_ROOT_DIR )
* Added `--squash` option whe building docker images
* Minor fix for tagging images to ensure the image exists
* Added force option when setting / removing global cli ENVs
* added force option to confirmExec helper
* Overrides asking the user to confirm an operation
**Test 1**
* Pull this PR and run the tests => `keg cli && keg pr 27 && keg cli test`
**Test 2**
* Test adding and remove global envs
*  Run the cmd `keg cli env set --key MY_TEST_ENV --value duper`
* It …
=> fix: Cleanup

package.json, src/utils/docker/compose/addComposeConfigs.js, src/utils/task/globalOptions.js
* The keg-cli should allow custom docker-compose config files defined from envs
* The current code is intended to allow this but, it broken
* Fix the keg-cli to allow loading custom docker-compose config files defied from envs
* `src/utils/docker/compose/addComposeConfigs.js`
* Fixed the loading of compose configs from ENVs
* `src/utils/task/globalOptions.js`
* Updated the default env to be `development`
* We will switch to `develop` eventually, but as for now it should be `development`
* Pull this branch locally => `keg cli && keg pr 33`
* Pick a linked tap of choice, I used `keg-herkin`
* In the taps `container folder`, add a new file called `docker-compose-development.yml`
* [Looks like this](http://snpy.in/3cnNsr)
* Really the name of the file could be anything, because we define the …
=> Hotfix Compose Configs

package.json, src/constants/docker/loaders.js
[Semver-Status] patch
* Load custom envs based on the containers name from the `~/.kegConfig` folder
=> Hotfix(loaders): Allow custom ENVs by container name

containers/proxy/values.yml, docs/images.md, src/__mocks__/libs/docker/data.js, src/tasks/docker/package/package.js, src/tasks/proxy/attach.js, src/utils/task/checkLinkedTaps.js
* Just fixing and adding a few things
* `containers/proxy/values.yml`
* `keg proxy att` was failing for two reasons, this was one of them
* it couldn't find the container name in the context 
* `src/tasks/proxy/attach.js`
* this was the other reason: `bash` isn't available in the proxy container, but `/bin/sh` is, so I changed it to use that as the `cmd` default
* `docs/images.md`
* just uploading the docker images workflow that Lance wrote a few months ago
* I did add one section at the end about building images locally'
* `src/tasks/docker/package/package.js`
* previously, whenever you ran the `pack` command but the container didn't exist, keg-cli would output a very unhelpful error message about a null/undefined value
* I just added a check for that and a more helpful error message
* …
=> General updates

containers/proxy/docker-compose.yml, containers/proxy/values.yml
* We don't want the proxy being restarted by watchtower
* Added label to tell watchtower to ignore the proxy
* ssh onto the keg staging server
* ensure the `keg-cli` is on this branch (`keg pr 48`)
* run `keg watchtower start --debug --runOnce --att`
* verify that the logs do not mention it pulling the `traefik` image/container at all
=> Watchtower proxy

containers/core/mutagen.yml, containers/tap/mutagen.yml, src/libs/mutagen/config.js, src/libs/mutagen/helpers.js
**Ticket**: [ZEN-450](https://jira.simpleviewtools.com/browse/ZEN-450)
> This PR should be tested in conjunction with these PRs
> [keg-hub](https://github.com/simpleviewinc/keg-hub/pull/147)
> [tap-events-force](https://github.com/simpleviewinc/tap-events-force/pull/127)
* Native / Mobile apps for keg-core have not been working for a while
* This needs to be fixed before we can start work for VisitApps
* Current issues
* Fonts don't load properly, and cause errors
* Parts of Re-Theme can not be resolved within the Native App
* `containers/**/mutagen.yml`
* Updated to not include the auto-generated `index.js` files instead of all files
* `src/libs/mutagen/config.js`
* Added ability completely override the default mutagen config instead of merging
* Requires adding a `mergeDefault: false` …
=> Zen 450 fix native apps

docs/docker/envs.md, src/utils/helpers/__tests__/checkEnvConstantValue.js, src/utils/helpers/checkEnvConstantValue.js, src/utils/services/composeService.js, src/utils/services/proxyService.js, src/utils/services/startService.js, src/utils/services/stopService.js
* There are some cases where we need to disable some of the default keg-cli functionality
* I added some envs to allow this
* Added more docs about `ENV`'s
* Added envs
* `KEG_AUTO_DOCKER_EXEC` - disables auto docker exec call
* `KEG_AUTO_SYNC` - disables auto mutagen sync creation
* `KEG_USE_PROXY` - disables checking the keg-proxy
* Added helper for check if an ENV value matches a passed in value
**Setup**
* Pull this pr => `keg cli && keg pr 52`
* Pick a tap, I used `tap-events-force`
**Test 1**
* Kill the tap if it's running => `keg evf kill`
* Add the `KEG_AUTO_DOCKER_EXEC: false` env to the taps values.yml file
* Run the taps start command `keg evf start`
* Ensure it starts the container, but does **NOT** run the exec command
* [Looks like this](http://snpy.in/G4z0Ep)
**Test 2**
* …
=> Add constants checking

containers/components/docker-compose.yml, containers/components/run.sh, containers/components/values.yml, containers/core/docker-compose.yml, containers/core/run.sh, containers/core/values.yml, containers/tap/docker-compose.yml, containers/tap/run.sh, containers/tap/values.yml, src/tasks/docker/package/package.js
**Ticket**: [ZEN-609](https://jira.simpleviewtools.com/browse/ZEN-609)
* This PR should be reviewed along side [this keg-herkin pr](https://github.com/simpleviewinc/keg-herkin/pull/41)
* This PR should be reviewed along side [this tap-evf pr](https://github.com/simpleviewinc/tap-events-force/pull/129)
* This PR should be reviewed along side [this keg-hub pr](https://github.com/simpleviewinc/keg-hub/pull/152)
> This is part 2 of the overall task.
> In this part, it updates the run.sh scripts of the docker images
> The scripts now check the `NODE_ENV` and run a different command based on that
* When we run our docker packages on the staging server, there are a number of features that we don't need, like running in development modes
* These features slow down the execution, and in some cases …
=> Zen 609 automate packages - Part 2

package.json, src/__mocks__/proxy/index.js, src/__mocks__/proxy/routes.js, src/tasks/proxy/list.js, src/tasks/proxy/open.js, src/tasks/proxy/proxy.js, src/utils/proxy/filterProxyRoutes.js, src/utils/proxy/getProxyRoutes.js, src/utils/proxy/index.js, yarn.lock
* Sometimes it's a pain to figure out the url to a running application
* Currently we use the Traefik Admin UI, but there are no direct links to the apps
* We have to go to the Admin UI in the borwser
* Find the container route, and navigate to its page
* Then copy and paste the url from the displayed rule, which is not always super clear
* Make it easy to open apps in a browser that are registered to the proxy
* Added to tasks to the proxy tasks that allow for opening a registered proxy route
* `keg proxy list` => Lists all registered routes
* Hides all internal routes by default, except for the the Admin UI route
* Allows a filter option to filter the results
* Using the filter includes internal routes
* `keg proxy open` => Opens a route's url in the browser
* Allows a context option to …
=> Proxy Route Tasks

repos/cli-utils/TODO.md, repos/cli-utils/mocks.js, repos/cli-utils/package.json, repos/cli-utils/src/commands/__tests__/commands.js, repos/cli-utils/src/commands/commands.js, repos/cli-utils/src/fileSys/fileSys.js, repos/cli-utils/yarn.lock
* When using the keg-cli utils in another app and writing tests; It would be helpful to allow importing the mocks from this repo
* There are times when we don't want to spawn a new process when running a cmd. It would be nice to have the ability to capture the output without out passing in events
* Include the mocks in th npm package
* Add a way to run commands and capture the output without passing callback methods
* `repos/cli-utils/mocks.js`
* Export the `__mock__` folder
* `repos/cli-utils/package.json`
*  Include the `mocks` in the NPM package
* Update `jsutils`
* `repos/cli-utils/src/commands/commands.js` 
* Add argument for using the `asyncCmd` instead of `spawnCmd`
*  Export `execCmd` so it can be used directly
* `repos/cli-utils/src/fileSys/fileSys.js`
* Fixed a fileSys bug
* Run …
=> Kutils 0.1.0 fa923bc

repos/cli-utils/package.json, repos/cli-utils/yarn.lock
* spawn-cmd uses tree-kill to ensure child processes are terminated. 
* There's a security issue with an older version of tree-kill, that's used by an older version of spawn-cmd
* This fixes the security issue by updating the spawn-cmd version in cli-utils
=> Update the spawn-cmd version in cli-utils

docs/docker/envs.md, repos/cli-utils/src/network/__tests__/getAddresses.js, repos/mutagen-lib/src/config.js, src/tasks/docker/build.js, src/utils/services/composeService.js, src/utils/task/options/buildOptions.js
* Fix issue where a tap's base image is not from the configured docker provider
* Now uses what ever `KEG_BASE_IMAGE` is set to
* This means the `KEG_BASE_IMAGE` is required to be a full url or it will use dockers default which is `dockerhub.io`
* Fix issue when mutagen config overrides is an empty object, which causes the defaults to not be set
* Fix issue where the command to be executed in a docker container can not be found in some cases 
* Add some docs / notes about `KEG_BASE_IMAGE`
* Fixed issue in the compose service that was using the wrong image when getting the docker run command
**IMAGE ENV Notes**
* It was pulling `IMAGE`  ENV, which really should be removed at some point
* With migration over to `KEG_IMAGE_FROM`, the `IMAGE` env should not longer be needed
* It's still being …
=> Base Image and Container Command fixes

docs/docker/envs.md, repos/cli-utils/src/commands/__tests__/commands.js, repos/cli-utils/src/commands/commands.js, repos/cli-utils/src/network/__tests__/getAddresses.js, repos/git-lib/yarn.lock, repos/mutagen-lib/src/config.js, src/tasks/docker/build.js, src/utils/services/composeService.js
* cli-utils runCmd had some bugs that needed fixed
* Also added more tests for it
* Added fix for one of the network tests that was failing due to a mock
* Updated how runCmd calls the methods from `spawn-cmd`
* Fixed issues with passing events
*  Ensure it returns the correct response when calling the execCmd
* Added more tests
* Pull this PR => `keg cli && keg pr 80`
* Move to the cli-utils repo => `keg cli && cd repos/cli-utils`
* Run `yarn test`
* Ensure all tests pass
=> cli-utils fix run cmd

repos/args-parse/src/__mocks__/testTasks.js, repos/args-parse/src/__tests__/argsParse.js, repos/args-parse/src/args/ensureArgs.js, repos/args-parse/src/options/checkValueType.js
* Fix bug in args-parse causing the default value to not be set when
* The default value is defined for the option 
* The type is defined for the option
* No value is passed for the option when being parsed
* Add more test cases for bug defined in Goal section
* Add comments to `ensureArg` method to help define what it's doing
* Add validate check to `checkValueType`
* Checks if the value does not exist, and the default does
* In this case it returns the default value
* It does not `type` check the default value
* At first I set it so it would also `type` check the `default value`, but there's a problem with this:
* The consumer can **not** define the `default value`
* If the `default value` does **not** match the defined `type`, it can cause issues when **no** `value` is passed
* Really …
=> fix(bug): Use default value when type is defined

repos/cli-utils/package.json, repos/cli-utils/src/index.js, repos/cli-utils/src/network/__mocks__/getAddresses.js, repos/cli-utils/src/network/__tests__/getAddresses.js, repos/cli-utils/src/network/getAddresses.js, repos/cli-utils/src/network/getHostIP.js, repos/cli-utils/src/network/getPrivateIPs.js, repos/cli-utils/src/path/__tests__/getPackageRoot.js, repos/cli-utils/src/path/getPackageRoot.js, repos/cli-utils/src/path/index.js, repos/cli-utils/src/tap/__tests__/getTapRoot.js, repos/cli-utils/src/tap/getTapRoot.js, repos/cli-utils/src/tap/index.js
* Move two utilities from `tap-snack` to `cli-utils`
* migrated from [this PR](https://github.com/simpleviewinc/tap-snack/pull/5) as part of review feedback
* `repos/cli-utils/src/path/getPackageRoot.js`
* gets the root path of a package 
* `repos/cli-utils/src/tap/getTapRoot.js`
* gets the root path of a tap
* `repos/cli-utils/src/network` 
* I noticed some of these functions I wrote were using keywords that are reserved in strict-mode or will be reserved in the future, so I updated it to use non-reserved keywords
* ensure tests pass
=> More cli utils

repos/parse-config/package.json, repos/parse-config/src/template/template.js
* Fix an issue preventing `va-platform-backend` container from running
* The `va-platform-backend` container is using `parse-config`, which expects the keg global config, which is not in the container. We just need it to use an empty object in that case.
* `repos/parse-config/src/template/template.js`
* added a parameter to toggle the keg-config requirement
* verify tests pass
=> parse-config: Remove keg global config requirement

repos/mutagen-lib/src/sync.js
**Ticket**: [VIS-1107](https://jira.simpleviewtools.com/browse/VIS-1107)
* Sometimes the `keg-boot` service technically "fails" on an EC2 instance when booting
* it happens because the `mutagen-lib`'s `list` function returns undefined, right at boot. Something with mutagen isn't available at this time, so it causes exceptions to be thrown later in the call stack.
* it doesn't actually break anything, though. The keg-boot service still ultimately runs correctly and starts the package with working mutagen syncs. But because this initial error was thrown, the `keg-boot` service was flagged as "failed" in `systemd`
* Ensure the mutagen-lib `list` functions returns an empty array if no syncs are found, so that functions expecting an array don't throw errors
* `repos/mutagen-lib/src/sync.js`
* …
=> Mutagen list fix

package.json, src/utils/docker/buildExecParams.js
* Fix sync actions
* Update the version
* Remove the name option from sync-action params
* Causes docker exec to fail
* Run cmd `keg evf start --sync core:install`
* Ensure the sync action runs as expected
* Run cmd `keg evf start --sync core:install,resolver:install`
* Ensure all sync actions run as expected
=> Hotfix v5 2 1

containers/base/defaults.env, scripts/ci/ci.env, scripts/cli/updates/5.2.1.sh, scripts/cli/updates/5.2.2.sh, scripts/setup/defaults.env, src/__mocks__/injected/injectedTest.js, src/utils/services/startService.js, src/utils/task/options/startServiceOptions.js
* Fix Node Version
* The `5.2.0` update script and the defaults had the node version set to `14.7`
* This should have been `14.17`
* The update was from `14.16` up to `14.17`, but instead it down graded to `14.7` 
* These change fix that by setting the correct node version, which is `14.17`
* Fix Recreate
* This option was being ignored in the start service
* This update adds a check to see if it exists, then uses it when it does
* If recreate does not exist, then is uses the `isNewImage` variable
* If `isNewImage` === `true`, then a new image is created
* Else it reuses the same image as before
* `containers/base/**` && `scripts/**`
* Update the node version to `14.17-alpine`
* `src/utils/services/startService.js`
* Check the params for the `recreate` option
* Ensure that value is used …
=> fix(node) Set node to v14.17 and fix recreate option
